#!/bin/bash
-rwxr--r-- 1 root root 16 Apr 13 11:20 0-current_working_directory
-rwxr--r-- 1 root root 15 Apr 13 11:29 1-listit
-rwxr--r-- 1 root root 17 Apr 13 11:31 2-bring_me_home
-rw-r--r-- 1 root root 18 Apr 13 11:32 3-listfiles
-rw-r--r-- 1 root root 13 Apr 13 11:18 README.md
